### PR TITLE
Argument formatting of arrays

### PR DESCRIPTION
**Pull request by ursenzler**
I changed the formatting of scenario arguments from `Example`s in the report to match the xUnit formatting.

I took the `ArgumentFormatter` from xUnit to format the arguments in the test report. The code is copied because the class is internal to xUnit. Maybe we could make a pull request to make the class public?

I used the `Reflector` from xUnit to convert the arguments from `Example`s to the type specified in the `Scenario` method.

Please provide feedback for:
- is the spec written in the correct way (`ArgumentFormatting`). I'm not sure I understood this `Feature` construct correctly.
- The code converting the arguments is not covered enough by tests in my opinion, but where would I add these tests? The class where I added the code has no unit tests (`MethodInfoExtensions`).

connects to #267

### CODE REVIEW

**Comment by adamralph** [comment]
@ursenzler thanks for this! I'll get onto it ASAP, but first I want to concentrate on getting your other PR merged - https://github.com/FakeItEasy/FakeItEasy/pull/528

**Comment by adamralph** [comment]
re #267

**Comment by adamralph** [comment]
@ursenzler

> I took the ArgumentFormatter from xUnit to format the arguments in the test report. The code is copied because the class is internal to xUnit. Maybe we could make a pull request to make the class public?

@bradwilson - would you accept a PR making `ArgumentFormatter` public?

**Comment by adamralph** [comment]
@ursenzler 

> - is the spec written in the correct way (ArgumentFormatting). I'm not sure I understood this Feature construct correctly.

The abstract `Feature` class provides methods for executing the scenarios contained in a given `type` and collecting the messages (e.g. test results) that are received. In the case of your new scenarios, you don't need the base class, since you are making assertions using the context of the currently executing scenario. It's an unconventional way to write the scenarios, but I think it's fine. It proves what it needs to prove.

> - The code converting the arguments is not covered enough by tests in my opinion, but where would I add these tests? The class where I added the code has no unit tests (MethodInfoExtensions).

Can you explain why the change to `MethodInfoExtensions` is required? It seems unrelated to the argument formatting. In fact, I commented out this change and all the tests remain green.

**Comment by bradwilson** [comment]
> @bradwilson - would you accept a PR making ArgumentFormatter public?

Sure.

**Comment by ursenzler** [comment]
@adamralph the change to MethodInfoExtensions is needed to support typed arrays in examples. Without this change, only `object[]` is  supported. I took this approach from xUnit.
But I'm not 100% sure, that it is correct this way. That's why I wanted your feedback.

**Comment by ursenzler** [comment]
We are currently using a custom build with these changes in our project to test it in real life. Works so far.

**Comment by adamralph** [comment]
@ursenzler the acceptance test uses `string[] words, int[] numbers` and it still works without the `MethodInfoExtensions` change. What makes you say that only `object[]` is supported without the change?

**Comment by ursenzler** [comment]
@adamralph hmm, when I revert the changes in `MethodInfoExtensions` I get the following exception:

```
System.ArgumentExceptionObject of type 'System.Object[]' cannot be converted to type 'System.String[]'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Xbehave.Execution.Extensions.MethodInfoExtensions.<InvokeAsync>d__0.MoveNext() in MethodInfoExtensions.cs: line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__0.MoveNext() in c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs: line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Xbehave.Execution.ScenarioInvoker.<>c__DisplayClass17_1.<<InvokeScenarioMethodAsync>b__0>d.MoveNext() in ScenarioInvoker.cs: line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__0.MoveNext() in c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.core\Sdk\ExceptionAggregator.cs: line 90
```

Can you check that you ran the correct source code state?

**Comment by ursenzler** [comment]
@adamralph did you find time to check this?

**Comment by adamralph** [comment]
hi @ursenzler, apologies for the delay.

I just tried it and, indeed, I get the same failure as you. Second apologies, I don't know what on earth I did that first time round. I'll blame Visual Studio :wink: 

Would you mind rebasing your branch onto latest dev? As soon we have a green build, I'll be happy to merge.

**Comment by ursenzler** [comment]
@adamralph sure, I'll do this. 

Nevermind the delay, we already use a custom build with my changes ;-)

**Comment by ursenzler** [comment]
Uh, oh, I accidentally clicked Update branch and no there is a merge commit. Is this okay for you, or do you want me to rebase my changes onto another branch/pull request?

**Comment by adamralph** [comment]
@ursenzler np - I cherry picked your commits and into #284

**Comment by adamralph** [comment]
Commits merged in #284

**Pull request closed without merging**
