### PR TITLE
Add two tests to ensure IAsyncLifetime is support on collection fixtures

### PR DESCRIPTION
**Pull request by redoz**
It's not much, I created them because I thought it didn't work, but it turns out the bug was in my own code. Feel free to discard if you don't want/need them, no hard feelings :)

### CODE REVIEW

**Comment by redoz** [comment]
Not entirely sure why that failed, seems unrelated to my changes?

**Comment by adamralph** [comment]
Thanks @redoz. I'll take a closer look ASAP.

**Comment by adamralph** [comment]
Thanks @redoz!

**Comment by redoz** [comment]
No worries, hopefully my next PR will be a bit more substantial :)

**Pull request merged**
