### PR TITLE
fix for xunit 2.1

### PR DESCRIPTION
**Pull request by adamralph**
#271

### CODE REVIEW

**Comment by adamralph** [comment]
@bradwilson if you have a moment, I'd appreciate your opinion on this.

Key points:
- I've upped the dependency on xunit from `[2.0.0,3)` to `[2.1.0,3)` on the basis that, effectively, there is a bug in xbehave 2.0 (cannot upgrade to later versions of xunit) which can only be fixed by a move to xunit 2.1. I guess it _may_ be back compatible with xunit 2.0 (I'm not sure if the double assembly inclusions via the reference and props would clash with each other) but IMHO the ROI of validating that isn't worth it.
- I've removed the use of props entirely, since xbehave currently only supports net45. I noticed that in xunit you are still providing dummy `_._` build files for TFN's which don't need them but I presume this is purely due to the presence of real files for some of the TFNs. In the case of xbehave no build files are currently required. The next minor release of xbehave will introduce the same TFN's as xunit 2.1 so I guess I will have to re-introduce the build folder, but until then YAGNI. As far as you know, will the removal and reintroduction cause any problem in the upgrade path?

**Comment by bradwilson** [comment]
> I've upped the dependency on xunit from [2.0.0,3) to [2.1.0,3) on the basis that, effectively, there is a bug in xbehave 2.0 (cannot upgrade to later versions of xunit) which can only be fixed by a move to xunit 2.1.

You can use the 2.1 runners to run 2.0 code (and 1.x code). They are intended to be independent, and [our manual test suite](https://github.com/xunit/xunit.integration) does verify that.

That said, so long as your users don't mind, I think upgrading to the 2.1 framework is beneficial, given the number of bugs and performance issues we've resolved.

> I've removed the use of props entirely, since xbehave currently only supports net45. I noticed that in xunit you are still providing dummy _._ build files for TFN's which don't need them but I presume this is purely due to the presence of real files for some of the TFNs.

Which NUSPEC file(s) in particular do you mean? We have several. :-p I'm happy to review what you have and answer questions about why we do what we do.

**Comment by bradwilson** [comment]
Okay, I went back and looked and this is all we still have in 2.1 for props files:

https://github.com/xunit/xunit/blob/fe8d78df7cfec55ddab93c29ea96b0032ca998a8/src/xunit.core.nuspec#L78-L87

The reason those exist is for the three platforms that we support with the Visual Studio runner. In addition to getting a copy of `xunit.execution.dotnet.dll` (as befits the target platform), it also ensures that the user gets an additional (unlinked) copy of `xunit.execution.desktop.dll`. The reason for that is that all unit test discovery (for the UI) is done with the desktop CLR. We have to load the user's unit tests into the desktop CLR and discover against them, with the desktop DLL (because we also must have app domain support, to prevent the DLL from being locked).

I wouldn't think you would need to duplicate this. If your users are already linking against the `xunit.core` NuGet package, they're already getting the desktop DLL copy they need.

**Comment by adamralph** [comment]
@bradwilson thanks for the valuable input.

I pretty much figured out what you were doing with the props files but it's good to get confirmation.

I think I'll stick with linking xbehave 2.0.1 against xunit 2.1. I wasn't so much worried about the runners (I guessed that you'd probably ensured 2.1 runners are fine with 2.0), it was more to do with the fact that, if xbehave 2.0.1 was linked to xunit 2.0, xunit.execution.desktop would be copied to the output directory by two mechanisms; the reference in xbehave, and the props from xunit. It probably _would_ work just fine, but I don't want to temp fate, given the various vesions of VS and NuGet out there in the wild. :worried:

I'll push this out as a beta and ask the issue reporter to test the upgrade path.

**Comment by adamralph** [comment]
Replaced by #274

**Pull request closed without merging**
