### PR TITLE
upgrade to 2.4.0-beta.1.build3958

### LINKED ISSUE #423: Link against xUnit.net 2.4

### PR DESCRIPTION
**Pull request by adamralph**
Connects to #423.

### CODE REVIEW

**Comment by blairconrad** [comment]
@adamralph, what's with the NuGet install failure? I see the packages in nuget.org gallery, but can't list them using nuget.exe to save my life…

**Comment by adamralph** [comment]
@blairconrad I've no idea. It's really weird. At the moment, the NuGet gallery is my prime suspect. 😉

**Comment by adamralph** [comment]
I think I know what it is. xunit is using a SemVer 2.0 pre-release identifier, with dots in it. Older NuGet clients don't understand that, and they don't see those versions. Something in the AppVeyor environment must be older than what I have on my machine, because It Works On My Machine™.

**Comment by adamralph** [comment]
https://twitter.com/adamralph/status/967090194955624448

**Comment by blairconrad** [comment]
Intriguing. Decidedly does _not_ work on my machine. Even with nuget.exe 4.5.1 and dotnet SDK 2.1.3. (in FakeItEasy, not xBehave. I should check out the differences).

**Comment by clairernovotny** [comment]
I think this is because you're building on the VS 2015 image and it's defaulting to the v2 NuGet endpoint. Specify `image: Visual Studio 2017` at the beginning of your yaml file to use the VS 2017 image.

**Comment by adamralph** [comment]
I switched to VS2017 (in the UI) for https://ci.appveyor.com/project/adamralph/xbehave-net/build/737-fdrlaees and it made no difference. I assume `appveyor.yml` doesn't replace the UI config, but masks it?

**Comment by blairconrad** [comment]
FWIW, I removed my old config file, which included a v2 endpoint, and the autogenerated one, which pointed at https://api.nuget.org/v3/index.json, worked a treat. Thanks, @onovotny.

**Comment by adamralph** [comment]
OK, I switched to VS 2017 in `appveyor.yaml` and that has indeed fixed it. So it seems like none of the UI settings apply when `appveyor.yaml` is present, which is news to me. Switching to VS 2017 was the first thing that occured to me but my assumption about the UI settings still having an effect threw me off course. Thanks @onovotny for putting me back on course!

**Pull request merged**
